spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_test?useUnicode=true&characterEncodin=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# 配置日志输出级别
logging:
  level:
    com.quanmin.paresfile: debug

upload:
  # 上传云的位置
  baseUrl: /usr/local/myself/java_soft/nginx/static/file
