spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.1.38:3306/cloudclinic?useUnicode=true&characterEncodin=utf-8&useSSL=false&serverTimeout=Asia/Shanghai
    username: hjc
    password: hjc

# 配置日志输出级别
logging:
  level:
    com.quanmin.paresfile: debug

upload:
  # 上传云的位置
  baseUrl: /usr/local/myself/java_soft/nginx/static/file
